# Generated by Django 6.0 on 2025-12-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0003_livewebinar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='recorded/covers/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='recorded/previews/')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('access_type', models.CharField(choices=[('LIFETIME', 'Lifetime'), ('LIMITED', 'Limited Time')], default='LIFETIME', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='RecordedWebinarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(help_text='Paragraphs separated by new lines')),
                ('why_attend', models.TextField(help_text='One point per line')),
                ('who_benefit', models.TextField(help_text='One point per line')),
                ('areas_covered', models.TextField(help_text='One point per line')),
                ('format', models.CharField(default='High-quality streaming', max_length=100)),
                ('refund_policy', models.CharField(default='100% Money Back Guarantee', max_length=255)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recorded_webinars.recordedwebinar')),
            ],
        ),
        migrations.CreateModel(
            name='RecordedWebinarPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('multi_user_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='recorded_webinars.recordedwebinar')),
            ],
        ),
    ]
