# Generated by Django 6.0 on 2026-01-12 17:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorded_webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedwebinarareacovered',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='recordedwebinarbenefit',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='recordedwebinaroverview',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='recordedwebinarwhyattend',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
