# Generated by Django 6.0 on 2025-12-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorded_webinars', '0001_initial'),
        ('webinars', '0005_alter_livewebinar_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedwebinar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_webinars', to='webinars.webinarcategory'),
            preserve_default=False,
        ),
    ]
