# Generated by Django 6.0 on 2025-12-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar')),
            ],
            options={
                'unique_together': {('session_key', 'webinar')},
            },
        ),
    ]
