# Generated by Django 6.0 on 2025-12-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recorded_webinars', '0001_initial'),
        ('webinars', '0003_livewebinar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('webinar_type', models.CharField(choices=[('LIVE', 'Live'), ('RECORDED', 'Recorded')], default='LIVE', max_length=10)),
                ('purchase_type', models.CharField(choices=[('LIVE_SINGLE', 'Live Single'), ('LIVE_MULTI', 'Live Multi'), ('RECORDED_SINGLE', 'Recorded Single'), ('RECORDED_MULTI', 'Recorded Multi'), ('COMBO_SINGLE', 'Combo Single'), ('COMBO_MULTI', 'Combo Multi')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar')),
                ('recorded_webinar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recorded_webinars.recordedwebinar')),
            ],
            options={
                'unique_together': {('session_key', 'webinar_type', 'live_webinar', 'recorded_webinar', 'purchase_type')},
            },
        ),
    ]
