# Generated by Django 6.0 on 2025-12-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('webinars', '0003_livewebinar_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='purchase_type',
            field=models.CharField(choices=[('LIVE_SINGLE', 'Live – Single'), ('LIVE_MULTI', 'Live – Multi'), ('REC_SINGLE', 'Recorded – Single'), ('REC_MULTI', 'Recorded – Multi'), ('COMBO_SINGLE', 'Combo – Single'), ('COMBO_MULTI', 'Combo – Multi')], default='LIVE_SINGLE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('session_key', 'webinar', 'purchase_type')},
        ),
    ]
