# Generated by Django 6.0 on 2025-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='purchase_type',
            field=models.CharField(choices=[('LIVE_SINGLE', 'Live Single'), ('LIVE_MULTI', 'Live Multi'), ('RECORDED_SINGLE', 'Recorded Single'), ('RECORDED_MULTI', 'Recorded Multi'), ('COMBO_SINGLE', 'Combo Single'), ('COMBO_MULTI', 'Combo Multi')], max_length=20),
        ),
    ]
