# Generated by Django 6.0 on 2025-12-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='webinars/instructors/')),
            ],
        ),
        migrations.CreateModel(
            name='LiveWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(upload_to='webinars/covers/')),
                ('start_datetime', models.DateTimeField()),
                ('time_display', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('ENDED', 'Ended')], default='UPCOMING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.instructor')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WebinarAreaCovered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('live_multi_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_multi_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('combo_single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('combo_multi_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='webinars.livewebinar')),
            ],
        ),
        migrations.CreateModel(
            name='WebinarWhyAttend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('webinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar')),
            ],
        ),
    ]
