# Generated by Django 6.0 on 2025-12-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livewebinar',
            name='price_usd',
        ),
    ]
