# Generated by Django 6.0 on 2025-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0002_remove_livewebinar_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='livewebinar',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
