# Generated by Django 6.0 on 2026-01-13 05:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0003_fix_richtext_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinarareacovered',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='webinarbenefit',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='webinaroverview',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='webinarwhyattend',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
