# Generated by Django 6.0 on 2025-12-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_webinarcategory_livewebinar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewebinar',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webinars', to='webinars.webinarcategory'),
        ),
    ]
