# Generated by Django 6.0 on 2026-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0004_alter_webinarareacovered_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livewebinar',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional – upload only if needed', null=True, upload_to='webinars/covers/'),
        ),
    ]
