# Generated by Django 6.0 on 2026-01-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinars', '0005_alter_livewebinar_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='livewebinar',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Mark this webinar as Test / Demo only'),
        ),
    ]
