# Generated by Django 6.0 on 2026-01-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_checkout_order'),
        ('subscriptions', '0001_initial'),
        ('webinars', '0004_alter_webinarareacovered_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webinars.livewebinar'),
        ),
    ]
