# Generated by Django 6.0 on 2026-01-30 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_subscription_plan_alter_orderitem_webinar'),
        ('recorded_webinars', '0002_alter_recordedwebinarareacovered_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='webinar',
            new_name='live_webinar',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(default='PAYPAL', max_length=30),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='recorded_webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recorded_webinars.recordedwebinar'),
        ),
    ]
